pool:
  name: Arm64
  vmImage: 'ubuntu-20.04'

trigger:
- main
resources:
- repo: self
variables:
  imagePullSecret: 'regcred'
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerConnection'
        repository: 'manoelvsneto/ebx'
        command: 'buildAndPush'
        tags: '$(Build.BuildId)'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

    - task: KubernetesManifest@0
      displayName: Create imagePullSecret
      inputs:
        kubernetesServiceConnection: K8SOracleCloud
        action: createSecret
        secretName: $(imagePullSecret)
        dockerRegistryEndpoint: 'DockerConnection'
    
    - task: PublishPipelineArtifact@1
      displayName: Publish Report
      inputs:
        artifact: '_Ebx.WebApi'
        publishLocation: 'pipeline'
    
    - task: KubernetesManifest@0
      displayName: Deploy to Kubernetes cluster
      inputs:
        kubernetesServiceConnection: K8SOracleCloud
        action: deploy
        manifests: |
          $(Build.SourcesDirectory)/Ebx.WebApi/deployment.yaml
          $(Build.SourcesDirectory)/Ebx.WebApi/service.yaml
          $(Build.SourcesDirectory)/Ebx.WebApi/ingress.yaml
        imagePullSecrets: |
          $(imagePullSecret)
        containers: 'manoelvsneto/ebx:$(Build.BuildId)'
    - task: DockerCompose@1
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Assinatura do Visual Studio Enterprise(2)(df29ae38-c766-49c6-bffe-6ecb1fccc959)'
        azureContainerRegistry: '{"loginServer":"archse.azurecr.io", "id" : "/subscriptions/df29ae38-c766-49c6-bffe-6ecb1fccc959/resourceGroups/MCTResourceGroup/providers/Microsoft.ContainerRegistry/registries/archse"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: Push services
        includeSourceTags: true