name: Trigger auto deployment for ebx

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ebx-AutoDeployTrigger-31e074e4-d613-44eb-9f78-2f102a8b8bea.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.EBX_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EBX_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EBX_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.EBX_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EBX_REGISTRY_PASSWORD }}
          containerAppName: ebx
          resourceGroup: MCTResourceGroup
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


