name: Trigger auto deployment for ebx-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ebx-container-app-AutoDeployTrigger-5721f52b-d768-4d1f-9d9b-4d7619358868.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.EBXCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EBXCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EBXCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.EBXCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EBXCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: ebx-container-app
          resourceGroup: MCTResourceGroup
          imageToBuild: manoelvsneto/ebx-container-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


